### ISSUE TITLE
导入不了

### ISSUE THREAD

**Issue by wanghaisheng** [boluokk/e7Helper#2]
![image](https://github.com/boluokk/e7Helper/assets/2363295/eee907f3-c141-4b1b-a271-673de627a308)

我换了最新的精灵页不支持

**Comment by wanghaisheng** [comment]
似乎目录结构调整了

**Comment by boluokk** [comment]
![image](https://github.com/boluokk/e7Helper/assets/71599104/d1d61d90-e6e4-4126-9b1e-4b21c24ad72b)
